package com.tools20022.repository.catalogue.msgdef.tsmt;

import com.tools20022.repository.dict.msg.MessageIdentification1;
import com.tools20022.repository.dict.msg.ReportLine1;
import java.util.Optional;

/**
 * Scope The IntentToPayReport message is sent by the matching application to
 * the two primary banks after receiving an IntentToPayNotification message.
 * This message is a report per transaction that were referenced in the
 * IntentToPayNotice message. For each transaction, the matching application has
 * accumulated the amounts present in all previous IntentToPayNotice messages
 * and reports the total. Usage The IntentToPayReport message is a report that
 * is automatically generated by the matching application following an
 * IntentToPayNotice message. No response is expected.
 */
public class IntentToPayReportV01 {

	private MessageIdentification1 ReportIdentification;
	private Optional<ReportLine1> ReportedItems;

	public MessageIdentification1 getReportIdentification() {
		return ReportIdentification;
	}

	public void setReportIdentification(
			MessageIdentification1 ReportIdentification) {
		this.ReportIdentification = ReportIdentification;
	}

	public Optional<ReportLine1> getReportedItems() {
		return ReportedItems;
	}

	public void setReportedItems(Optional<ReportLine1> ReportedItems) {
		this.ReportedItems = ReportedItems;
	}
}